name: vibe check

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set da Python shit
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'

      - name: Install deez Python dependencies nuts 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run dem tests
        working-directory: ./app
        run: pytest
