name: Manual Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.0.0)'
        required: true
      name:
        description: 'Release name (e.g. HolyCompress 1.0.0)'
        required: true

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PyInstaller
        run: python -m pip install pyinstaller

      - name: Build with build.py
        run: python build.py

      - name: Archive build output
        run: |
          cd dist
          zip -r "jpegcompress-${{ github.event.inputs.tag }}.zip" jpegcompress

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: ${{ github.event.inputs.name }}
          files: dist/jpegcompress-${{ github.event.inputs.tag }}.zip
